# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
