# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='news_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='question_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
